### ISSUE TITLE
Use start.duckduckgo.com as the default for that search engine. 

### ISSUE THREAD

**Issue by alanhoyle** [jcs/endless#49] opened 2017-11-28 20:15 UTC
https://start.duckduckgo.com/ would be a better choice than the current https://duckduckgo.com/ because it doesn't include the site description, in-page pop-ups, or the "Add to Safari" and "Learn More" buttons.

**Comment by jcs** [comment] 2017-11-28 20:16
Dupe of #48

**Closed as completed by jcs** 2017-11-28 20:16 UTC
